#!/bin/bash
#refreshes the PATH
source /root/.profile
source /root/.bashrc
#checks if its running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "This script must be run as root.\nExiting..." 
   exit 126
fi
#sets the path var
SP="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
#builds the executables for the compiled langs
$SP/build
#runs the compiled executable for div1.hs
./div1
#runs the compiled beam for welcome.erl
erl -noshell -s welcome start -s init stop
#runs the compiled executable for div2.nim
./div2
python3 h.py
node e.js
lua l1.lua
ruby l2.rb
#runs the compiled executable for o1.c
./o1
julia space.jl
#runs the compiled executable for w.go
./w
bash o2.bash
perl r.pl
php l3.php
#runs the compiled executable for d.rs
./d
./\!1
tclsh \!2.tcl
./bin/brainfuck/build/brainfuck \!3.bf
raku newline.raku
#runs the compiled classfile for credit.java
java credit
#runs the compiled bash script and pipes it to the unlambda interpreter because its weird
./contact | unlambda
elixir div3.exs
#runs the compiled jar for thank.kt
kotlin -classpath thank.jar ThankKt
#runs the compiled executable for sorry.swift
./sorry
#runs the compiled executable for div4.cpp
./div4
#deletes the compiled executables, the classfile, and the script
#oh yea and the beam
#aaaaaaaaaaand the jar
rm \!1 d o1 w credit.class contact div1 welcome.beam div1.o div2 div1.hi thank.jar sorry div4 a.out